# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171019_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileddocument',
            name='size_x',
            field=models.IntegerField(default=22615),
        ),
        migrations.AddField(
            model_name='tileddocument',
            name='size_y',
            field=models.IntegerField(default=17283),
        ),
    ]
